feat: 明示的にpasswordEncryptorを指定するようテスト用のコンポーネント定義を修正しました。
nablarch/nablarch-biz-sample-all pull request #12
Opened 2023-01-19 02:14 UTC by sukegawatakashitis

### 変更内容

-  明示的にpasswordEncryptorを指定するようテスト用のコンポーネント定義を修正しました。
- コメント修正しました。

2023-01-19 05:54 UTC, kumagoro1202 commented
`PasswordExpiredException`が業務日付のままです。

2023-01-19 06:05 UTC, sukegawatakashitis commented
> PasswordExpiredExceptionが業務日付のままです。

こちらで修正しました。
https://github.com/nablarch/nablarch-biz-sample-all/pull/12/commits/616bdf79841d70c2cbac6ecc006d9e654f4ba73d

2023-01-20 08:43 UTC, kumagoro1202 commented
テストクラスの業務日付という文言も修正してください。

2023-01-20 08:46 UTC, kumagoro1202 commented
テスト用のFixedBusinessDateProviderを使わなくなっているので削除してください。

2023-01-20 09:14 UTC, sukegawatakashitis commented
> テスト用のFixedBusinessDateProviderを使わなくなっているので削除してください。

こちらで修正しました。
https://github.com/nablarch/nablarch-biz-sample-all/pull/12/commits/214012fd5fea3e16176362316f4f09f0ba7d073d

2023-01-20 09:14 UTC, sukegawatakashitis commented
> テストクラスの業務日付という文言も修正してください。

こちらで修正しました。
https://github.com/nablarch/nablarch-biz-sample-all/pull/12/commits/c0616e33862499b737901da29acb6261f8fd2942

2023-01-20 09:23 UTC, kumagoro1202 requested changes

2023-01-20 09:23 UTC, kumagoro1202 commented on src/test/resources/unit-test.xml
> +  <!-- システム日付、固定日時を固定値に設定 -->
日本語おかしい。
「システム日付を固定値に設定」

2023-01-20 09:26 UTC, sukegawatakashitis commented on src/test/resources/unit-test.xml
> +  <!-- システム日付、固定日時を固定値に設定 -->
すみません。こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/12/commits/dd7bbecb6c36e7352c18f768c6381bfae0553806

2023-01-20 09:30 UTC, kumagoro1202 requested changes

2023-01-20 09:30 UTC, kumagoro1202 commented on src/main/java/please/change/me/common/authentication/SystemAccountAuthenticator.java
> +     * @param sysDate 現在日付（yyyyMMdd）
ここは変数名はsysDateでいいけど論理名は判定基準日のままでいいと思います。最初のメソッドの説明と整合性が取れなくなるので。

2023-01-20 09:33 UTC, sukegawatakashitis commented on src/main/java/please/change/me/common/authentication/SystemAccountAuthenticator.java
> +     * @param sysDate 現在日付（yyyyMMdd）
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/12/commits/3278e0ea87a123c467049c2403c40cc499cd966f

2023-01-20 09:34 UTC, kumagoro1202 approved these changes

2023-01-20 09:34 UTC, merged