[WIP] feat: 実装例集：検索結果の一覧表示：サンプルプロジェクトからのソース配置/調整
nablarch/nablarch-biz-sample-all pull request #13
Opened 2023-01-23 08:49 UTC by sukegawatakashitis

### 変更内容
- サンプルプロジェクトから、検索結果の一覧表示用のタグファイルを再配置しました。
  - taglibディレクティブを nbs に修正しました。
- tldファイルを再配置にあわせて、調整しました。

2023-01-26 04:40 UTC, kumagoro1202 requested changes

2023-01-26 04:40 UTC, kumagoro1202 commented on src/main/resources/META-INF/tags/listSearchResult/listSearchPaging.tag
> +
`pageNumberSubmitWrapperCss`という属性は現在の実装ではどこにも使われていません。削除してください。
同様にattributeディレクティブで宣言しているけど使ってないものがないか全部確認してください。

2023-01-26 04:40 UTC, kumagoro1202 commented on src/main/resources/META-INF/tags/listSearchResult/listSearchSubmit.tag
>          </c:if>
sortIdは渡されることがないです。削除してください。

2023-01-26 07:08 UTC, sukegawatakashitis commented on src/main/resources/META-INF/tags/listSearchResult/listSearchPaging.tag
> +
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/13/commits/55054803cb391a9429f5e8b4070a75258744e0b8
また、attributeディレクティブで宣言している属性について確認しました。

2023-01-26 07:09 UTC, sukegawatakashitis commented on src/main/resources/META-INF/tags/listSearchResult/listSearchSubmit.tag
>          </c:if>
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/13/commits/48e1654dfb9859d4401f9867ec1df81e0819385b

2023-01-26 10:40 UTC, kumagoro1202 requested changes

2023-01-26 10:40 UTC, kumagoro1202 commented on src/main/resources/META-INF/tags/listSearchResult/listSearchPaging.tag
> -<c:if test="${empty pagingCss}"><n:set var="pagingCss" value="nablarch_paging" scope="page" /></c:if>
なぜデフォルト値の設定消しているんですか？

2023-01-30 00:43 UTC, sukegawatakashitis commented on src/main/resources/META-INF/tags/listSearchResult/listSearchPaging.tag
> -<c:if test="${empty pagingCss}"><n:set var="pagingCss" value="nablarch_paging" scope="page" /></c:if>
確認したところ理由がわからず、誤って修正したと思われます。
こちらで元に戻しました。
https://github.com/nablarch/nablarch-biz-sample-all/pull/13/commits/d24e49b503419d9bc04a309da2f02e154fb198d7

2023-01-30 01:19 UTC, kumagoro1202 approved these changes

2023-01-30 01:19 UTC, merged