feat: 実装例集：データベースを用いたファイル管理機能サンプル：ソース改修
nablarch/nablarch-biz-sample-all pull request #19
Opened 2023-02-09 09:26 UTC by sukegawatakashitis

### 変更内容
- サンプルプロジェクト修正のため、データベースを用いたファイル管理機能をソース改修しました。

2023-02-10 07:21 UTC, kumagoro1202 requested changes

2023-02-10 07:21 UTC, kumagoro1202 commented on src/main/java/please/change/me/common/file/management/DbFileManagement.java
> +        } catch (SerialException e) {
SerialExceptionはSQLExceptionのサブクラスなので分ける意味がないです。

2023-02-10 07:21 UTC, kumagoro1202 commented on src/test/java/please/change/me/common/file/management/DbFileManagementTest.java
> +        statement.execute("DROP TABLE FILE_CONTROL CASCADE CONSTRAINTS");
FILE_CONTROLがない状態でテストが失敗します。

2023-02-10 07:21 UTC, kumagoro1202 commented on src/test/java/please/change/me/common/file/management/DbFileManagementTest.java
> +    void tearDown() throws Exception {
throwされるExceptionがありません。

2023-02-10 07:34 UTC, sukegawatakashitis commented on src/main/java/please/change/me/common/file/management/DbFileManagement.java
> +            System.out.println("!!!partInfo.size():" + partInfo.size());
すみません。消し忘れです。
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/774b553014a1486e6e920acbadb445a1e8217cdd

2023-02-10 07:34 UTC, sukegawatakashitis commented on src/main/java/please/change/me/common/file/management/DbFileManagement.java
> +    private SimpleDbTransactionManager dbManager;
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/e93920b179f16e68190c81aab890599c8d3b3330

2023-02-10 07:47 UTC, sukegawatakashitis commented on src/main/java/please/change/me/common/file/management/DbFileManagement.java
> +    public void delete(String fileControlId) {
こちらで削除しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/e78db0c57002a2bb27e59883f4da39c87c6bf066

2023-02-10 07:49 UTC, sukegawatakashitis commented on src/main/java/please/change/me/common/file/management/DbFileManagement.java
> +        } catch (SerialException e) {
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/bfb141b4993c0966053f83ddf37207d41e0b6f9b

2023-02-10 07:54 UTC, sukegawatakashitis commented on src/test/java/please/change/me/common/file/management/DbFileManagementTest.java
> +        statement.execute("DROP TABLE FILE_CONTROL CASCADE CONSTRAINTS");
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/d8a476205117b489746ad1d14f596e762ba24689

2023-02-10 07:56 UTC, sukegawatakashitis commented on src/test/java/please/change/me/common/file/management/DbFileManagementTest.java
> +    void tearDown() throws Exception {
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/521e6664f0a33fbfcc25302c9da8ce955a6a6606

2023-02-10 07:57 UTC, sukegawatakashitis commented on src/main/java/please/change/me/common/file/management/DbFileManagement.java
> +        BufferedInputStream bufferedInStream = new BufferedInputStream(inStream);
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/ce3ea4fa61334447c2704689744cbe6937cf5697

2023-02-13 01:03 UTC, kumagoro1202 requested changes

2023-02-13 01:03 UTC, kumagoro1202 commented on src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
> +  <component class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory" />
使っていないため不要

2023-02-13 01:03 UTC, kumagoro1202 commented on src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
> +  <component name="daoContextFactory" class="nablarch.common.dao.BasicDaoContextFactory" />
使っていないため不要

2023-02-13 02:39 UTC, sukegawatakashitis commented on src/main/resources/please/change/me/common/file/management/entity/FileControl.sql
> +    *
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/7596d21fceff5886ef727a25cb2bd7522647c9eb

2023-02-13 02:40 UTC, sukegawatakashitis commented on src/main/resources/please/change/me/common/file/management/entity/FileControl.sql
> +    *
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/a835a50edf10f82de5cffd968b767932e0f037d4

2023-02-13 02:41 UTC, sukegawatakashitis commented on src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
> +  <component name="daoContextFactory" class="nablarch.common.dao.BasicDaoContextFactory" />
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/c721482e24a2cc162a7de6383d5d8198b06e03c7

2023-02-13 02:50 UTC, sukegawatakashitis commented on src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
> +  <component class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory" />
こちらで修正しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/57e26a036d73544b0b5413c714f8832ff0df3517

2023-02-13 05:32 UTC, kumagoro1202 commented on src/main/resources/please/change/me/common/file/management/entity/FileControl.sql
> +    *
UPDATE文消えてないです。

2023-02-13 05:33 UTC, kumagoro1202 commented on src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
> +  <component class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory" />
transactionFactoryもです。

2023-02-13 05:40 UTC, sukegawatakashitis commented on src/test/resources/please/change/me/common/file/management/dbFileManagement.xml
> +  <component class="nablarch.core.db.statement.exception.BasicSqlStatementExceptionFactory" />
すみません。こちらで削除しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/3fb3126068cfc12a7e7a8820710b4f47c501e5a6

2023-02-13 05:41 UTC, sukegawatakashitis commented on src/main/resources/please/change/me/common/file/management/entity/FileControl.sql
> +    *
すみません。こちらで削除しました。https://github.com/nablarch/nablarch-biz-sample-all/pull/19/commits/af746660ac5d6b3412bfa45644423c9e1ca26478

2023-02-13 05:45 UTC, kumagoro1202 approved these changes

2023-02-13 05:45 UTC, merged